# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:\"#707070\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 100, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:\"#69DC9E\"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 70, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:\"#69DC9E\"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 130, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:\"#3B7455\"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 70, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:\"#69DC9E\"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 100, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:\"#69DC9E\"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 60, 471, 471))
        self.listWidget.setStyleSheet("background-color:\"white\";")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet(" font-size: 39px;\n"
"")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "VA"))
        self.pushButton_2.setText(_translate("MainWindow", "Віддзеркалення"))
        self.pushButton_3.setText(_translate("MainWindow", "що"))
        self.pushButton_4.setText(_translate("MainWindow", "Різкість"))
        self.pushButton_5.setText(_translate("MainWindow", "Ч/Б"))
        self.label.setText(_translate("MainWindow", "Зображення"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
